### ISSUE TITLE
Charging/Intercepting off-targets changes target of auto attacks

### ISSUE THREAD

**Issue by stako** [magey/wotlk-warrior#24] opened 2022-08-12 00:49 UTC
Charging or Intercepting a unit will cause auto attacks to start hitting the same unit, **even if it is not the current target**. [This video](https://puu.sh/JfKWv/9783315ff0.mp4) demonstrates by charging the `focus` unit. Note that my target never changes, it is always skull, however I am able to begin auto attacking X after having charged it, and no longer able to auto attack skull.

GetBuildInfo
3.4.0 45043 Aug 9 2022 30400

**Comment by CharWS** [comment] 2022-08-12 03:56
Looks like duplicate of: https://github.com/JamminL/wotlk-classic-bugs/issues/7

**Comment by magey** [comment] 2022-08-12 16:24
So, this behavior comes up every beta since classic - I guess it's tradition by now 😄

And as the issue Char linked says it's not a bug and consistent with original WotLK behavior.

**Closed as completed by magey** 2022-08-12 16:24 UTC
Labels: Not a bug
