### ISSUE TITLE
Taste for Blood sometimes skips a Rend tick when it should be off ICD

### ISSUE THREAD

**Issue by oliver-0** [magey/wotlk-warrior#22] opened 2022-08-07 03:55 UTC
#### Expected behaviour:
Taste for Blood ("Overpower proc") should proc from Rend damage with an ICD of 6s. On a fresh Rend, it should proc first at 3s (first tick), then again at the third tick (9s), fifth tick (15s) etc until the end of Rend.
[Reference video of 3.1.x+ Arms warrior showing expected behaviour - proccing reliably off 1st, 3rd, 5th ticks.](https://www.youtube.com/watch?v=cA3x6tXmFg4) (note: only consider the start of phase 1/2/etc for fresh Rends, as the player in this video throws off their proc timing by clipping the Taste for Blood ICD when reapplying Rend. He also seems to not be using Glyph of Rending, so his fifth tick is his final tick)

#### Current behaviour (on Wrath Pre-patch PTR): 
Occasionally Taste for Blood does not trigger on a Rend tick when it should be off cooldown (after 6s)

#### To reproduce:
Apply a fresh Rend to a target, witness that Taste for Blood occasionally skips a Rend tick.
[Here is a clip where it correctly procs off the first, third, and fifth ticks, (and incorrectly skips the last tick - missing one proc).](https://streamable.com/fwid2j)
[Another clip, this time the 2nd proc is late and the 3rd proc happens 6s later.](https://streamable.com/acztdk)
[Final clip reproducing the unexpected behaviour while not running Glyph of Rending, in case that was an issue. 2nd proc skips one tick.](https://streamable.com/062av4)

**Comment by magey** [comment] 2022-08-07 15:18
So, this bug was already discussed [over at Jammin's github](https://github.com/JamminL/wotlk-classic-bugs/issues/252) and I've demonstrated there that this behavior is consistent with original WotLK (you can see my video analysis and beta log breakdown there - Char and Bouk posted them) which makes this technically not a bug.

That said, it's extremely shitty having the main talent for your tree behave like that and I find it hard to believe it was intended to behave like that back then, so I'm going to leave this open here marked as a bug until we get an official response from Blizzard on whether they want to fix it or not.

**Comment by oliver-0** [comment] 2022-08-07 16:04
Didn't know about Jammin's repo, will have a look through that before reporting something next time - thanks.
Also glad (in a way) to see that there's conclusive evidence over there that this existed on live... Just need to convince Blizz to change it now ;)

Cheers.

**Comment by Mitchimus** [comment] 2022-08-23 01:34
![image](https://user-images.githubusercontent.com/43545579/186048527-f392035d-3251-4f39-80f8-47f0f836ffc8.png)
 5.984

![image](https://user-images.githubusercontent.com/43545579/186048748-0db114a3-b7ca-4a53-aa0e-33af8f21be93.png)
5.917

I have done some testing/logging of TFB/Rend interactions and found the inconsistency of missing a rend tick still to be in effect. Also have found it will sometimes proc earlier than 6s, which adds to the confusion of why this isn't functioning as stated in the talent. Hopefully Blizzard can fix this weird interaction and get this talent to function as stated - every 6 seconds,

**Comment by TheGroxEmpire** [comment] 2022-10-18 21:27
Seems to be fixed in build 3.4.0.46158.
[tfb_test.txt](https://github.com/magey/wotlk-warrior/files/9815232/tfb_test.txt)

**Closed as completed** 2022-10-20 17:58 UTC
Labels: Bug, Fixed
